Repository spesmilo/electrum, pull requests merged in 2018-06, with the labels that each got.

#3870 [WIP] Crash reports android
  gui/kivy/main_window.py
  gui/kivy/uix/dialogs/crash_reporter.py
  gui/qt/exception_window.py
  lib/base_crash_reporter.py
Labels: OS-android

#4463 Daemon: Fix preflight CORS request handling
  lib/jsonrpc.py
Labels: security

#3700 Add a warning about harmful code to the console
  gui/qt/console.py
Labels: enhancement, user-interface
