Repository spesmilo/electrum, pull requests merged in 2018-10, with the labels that each got.

#4727 qt: refresh gui with "F5"
  electrum/gui/qt/main_window.py
Labels: user-interface

#4753 restructure synchronizer
  electrum/address_synchronizer.py
  electrum/commands.py
  electrum/interface.py
  electrum/network.py
  electrum/synchronizer.py
  electrum/util.py
  electrum/verifier.py
  electrum/websockets.py
  run_electrum
Labels: topic-network

#4765 cli/rpc: 'restore' and 'create' commands are now available via RPC
  electrum/commands.py
  electrum/daemon.py
  electrum/keystore.py
  electrum/mnemonic.py
  electrum/tests/test_commands.py
  run_electrum
Labels: CLI/RPC

#4767 network: auto-switch servers to preferred fork (or longest chain)
  electrum/blockchain.py
  electrum/gui/kivy/main_window.py
  electrum/gui/qt/network_dialog.py
  electrum/interface.py
  electrum/network.py
  electrum/verifier.py
Labels: topic-network

#4773 Removal of macOS Info.plist. It isn't being used by anything.
  Info.plist
Labels: OS-mac, build/packaging
