Repository spesmilo/electrum, pull requests merged in 2019-11, with the labels that each got.

#5739 qt tx dialog: show dropdown for "export", instead of separate buttons
  electrum/gui/qt/transaction_dialog.py
Labels: Qt, user-interface

#5787 Return 401 from RPC server for missing auth
  electrum/daemon.py
Labels: CLI/RPC

#5774 Color-Code Addresses in Kivy UI
  electrum/gui/kivy/main.kv
  electrum/gui/kivy/uix/dialogs/tx_dialog.py
Labels: OS-android, enhancement, graphics, user-interface

#5809 wallet: better (outgoing) invoice "paid" detection
  electrum/address_synchronizer.py
  electrum/gui/kivy/main_window.py
  electrum/gui/kivy/uix/screens.py
  electrum/gui/qt/invoice_list.py
  electrum/gui/qt/main_window.py
  electrum/gui/qt/transaction_dialog.py
  electrum/json_db.py
  electrum/wallet.py
Labels: topic-payment-request, topic-wallet
