Repository spesmilo/electrum, pull requests merged in 2019-12, with the labels that each got.

#5820 ECDSA signatures: grind low R to match with Bitcoin Core (take 2)
  contrib/requirements/requirements.txt
  electrum/ecc.py
  electrum/ecc_fast.py
  electrum/tests/test_bitcoin.py
  electrum/tests/test_commands.py
  electrum/tests/test_lnutil.py
  electrum/tests/test_wallet_vertical.py
  electrum/transaction.py
Labels: topic-ECkeys, topic-transactions

#5822 qt receive tab: show plain bitcoin address
  electrum/gui/qt/address_list.py
  electrum/gui/qt/main_window.py
  electrum/gui/qt/request_list.py
  electrum/plugins/hw_wallet/qt.py
Labels: Qt, user-interface

#5830 wallet perf: significant speedup for make_unsigned_transaction and rel.
  electrum/base_wizard.py
  electrum/bip32.py
  electrum/keystore.py
  run_electrum
Labels: performance, topic-wallet

#5833 Qt: introduce BlockingWaitingDialog
  electrum/gui/qt/confirm_tx_dialog.py
  electrum/gui/qt/util.py
Labels: Qt

#5840 windows: when running from source, with py3.8+, load DLLs from '.dlls'
  .gitignore
  run_electrum
Labels: OS-windows

#5825 wallet: allow saving partial tx as local (if it has a txid)
  electrum/address_synchronizer.py
  electrum/gui/qt/transaction_dialog.py
  electrum/json_db.py
  electrum/lnworker.py
  electrum/wallet.py
Labels: topic-wallet

#5692 Trezor: support for Shamir backup and recovery
  contrib/requirements/requirements-hw.txt
  electrum/plugins/trezor/clientbase.py
  electrum/plugins/trezor/qt.py
  electrum/plugins/trezor/trezor.py
Labels: hw-trezor

#5460 keepkey: use libusb to enumerate devices instead of hid
  contrib/deterministic-build/requirements-hw.txt
  contrib/requirements/requirements-hw.txt
  electrum/plugins/keepkey/keepkey.py
Labels: hw-keepkey
