Repository spesmilo/electrum, pull requests merged in 2020-06, with the labels that each got.

#6198 enable streaming full UTXOs for all types of inputs
  electrum/plugins/trezor/trezor.py
  electrum/transaction.py
  electrum/wallet.py
Labels: hw-generic, topic-transactions

#6217 tx dialog: show various warnings if input amounts cannot be verified
  electrum/gui/kivy/uix/dialogs/tx_dialog.py
  electrum/gui/qt/transaction_dialog.py
  electrum/transaction.py
  electrum/wallet.py
Labels: topic-transactions

#6228 make targz sdist reproducible, rm zip
  .travis.yml
  README.rst
  contrib/build-linux/README.md
  contrib/build-linux/appimage/README.md
  contrib/build-linux/sdist/Dockerfile
  contrib/build-linux/sdist/README.md
  contrib/build-linux/sdist/build.sh
  contrib/build-linux/sdist/make_tgz
  contrib/deterministic-build/requirements-sdist-build.txt
  contrib/freeze_packages.sh
  contrib/make_packages
  contrib/requirements/requirements-sdist-build.txt
Labels: build/packaging, reproducible/deterministic builds

#6238 network: randomise the order of address subscriptions
  electrum/lnwatcher.py
  electrum/lnworker.py
  electrum/synchronizer.py
  electrum/util.py
Labels: topic-network, topic-wallet

#6261 Add mempool.space option for mainnet block explorer
  electrum/util.py
Labels: block-explorer
