Repository spesmilo/electrum, pull requests merged in 2020-09, with the labels that each got.

#6435 Save wallet DB after adding or removing payment requests
  electrum/commands.py
Labels: CLI/RPC

#6561 hardware devices: run all device communication on dedicated thread
  electrum/plugin.py
  electrum/plugins/bitbox02/bitbox02.py
  electrum/plugins/coldcard/coldcard.py
  electrum/plugins/digitalbitbox/digitalbitbox.py
  electrum/plugins/hw_wallet/plugin.py
  electrum/plugins/keepkey/clientbase.py
  electrum/plugins/keepkey/keepkey.py
  electrum/plugins/ledger/ledger.py
  electrum/plugins/safe_t/clientbase.py
  electrum/plugins/safe_t/safe_t.py
  electrum/plugins/trezor/clientbase.py
  electrum/plugins/trezor/trezor.py
Labels: hw-generic

#6593 win binary: build zbar ourselves
  contrib/build-wine/Dockerfile
  contrib/build-wine/build.sh
  contrib/build-wine/deterministic.spec
  contrib/build-wine/prepare-wine.sh
  contrib/make_libsecp256k1.sh
  contrib/make_zbar.sh
  electrum/qrscanner.py
Labels: OS-windows, build/packaging
