Repository spesmilo/electrum, pull requests merged in 2020-10, with the labels that each got.

#6635 CLI: allow specifying --wallet at any arg position, as before
  electrum/commands.py
  electrum/daemon.py
Labels: CLI/RPC

#6603 windows build: for the "setup" exe, put another "-debug" exe inside
  contrib/build-wine/deterministic.spec
Labels: OS-windows, build/packaging

#6645 android build: update list of apt deps for buildozer
  contrib/android/Dockerfile
Labels: OS-android, build/packaging

#6649 BitBox02 v9.2.0: support for signing messages and for p2wsh-p2sh legacy multisig accounts
  contrib/requirements/requirements-hw.txt
  electrum/plugins/bitbox02/bitbox02.py
Labels: hw-digitalbitbox

#6660 Remove phishing server
  electrum/servers.json
Labels: topic-network

#6685 bitcoin/transaction: construct_script, and clean-ups
  electrum/bitcoin.py
  electrum/coinchooser.py
  electrum/gui/qt/paytoedit.py
  electrum/lnsweep.py
  electrum/lnutil.py
  electrum/plugins/keepkey/keepkey.py
  electrum/plugins/ledger/ledger.py
  electrum/plugins/safe_t/safe_t.py
  electrum/submarine_swaps.py
  electrum/tests/test_transaction.py
  electrum/transaction.py
  electrum/wallet.py
Labels: topic-transactions

#6698 qt gui: send tab: change "Pay" button text to "Pay..."
  electrum/gui/qt/invoice_list.py
  electrum/gui/qt/main_window.py
Labels: user-interface
