Repository spesmilo/electrum, pull requests merged in 2021-06, with the labels that each got.

#7300 Android: Fix wallet backup
  electrum/gui/kivy/main_window.py
Labels: OS-android🤖

#5823 Qt address list: add "funded or unused" filter option
  electrum/gui/kivy/uix/dialogs/addresses.py
  electrum/gui/qt/address_list.py
Labels: user-interface 🔲

#7354 readme: add a "contributing" section, mentioning new irc
  README.rst
Labels: docs 📖

#7359 rephrasing, removal of revealer website links
  electrum/plugins/revealer/__init__.py
  electrum/plugins/revealer/qt.py
Labels: plugin-revealer ⬛
