Repository spesmilo/electrum, pull requests merged in 2021-07, with the labels that each got.

#7396 Don't cleanup lockfile if listen_jsonrpc is False
  electrum/daemon.py
Labels: CLI/RPC ▶

#7395 Add lightning tag for commands
  electrum/commands.py
Labels: CLI/RPC ▶

#7399 wallet: fire "request_status" event also when conf number changes
  electrum/address_synchronizer.py
  electrum/wallet.py
Labels: topic-wallet 👛

#7400 mac build: don't create __pycache__ folders
  contrib/build-wine/build-electrum-git.sh
  contrib/osx/make_osx
Labels: OS-mac, build/packaging 📦

#7403 Improve _mythread checks
  electrum/lnrater.py
  electrum/network.py
  electrum/util.py
Labels: topic-network 🕸

#7411 mac build: download python from python.org instead of using pyenv
  .gitignore
  contrib/osx/make_osx
Labels: OS-mac, build/packaging 📦

#7415 mac build: attempt at "reproducible" codesigned builds
  contrib/osx/README.md
  contrib/osx/apply_sigs.sh
  contrib/osx/compare_dmg
  contrib/osx/extract_sigs.sh
Labels: OS-mac, build/packaging 📦, reproducible/deterministic builds
