Repository spesmilo/electrum, pull requests merged in 2021-04, with the labels that each got.

#7178 kivy: implement freezing addresses
  electrum/gui/kivy/uix/dialogs/addresses.py
Labels: OS-android🤖, user-interface 🔲

#7187 android: update app icon; use "adaptive icons" on API 26+
  contrib/android/Dockerfile
  contrib/android/buildozer.spec
  electrum/gui/icons/android_electrum_icon_background.png
  electrum/gui/icons/android_electrum_icon_foreground.png
  electrum/gui/icons/android_electrum_icon_legacy.png
Labels: OS-android🤖

#7191 Prevent spaces from causing issues in make_osx
  contrib/osx/make_osx
Labels: OS-mac, build/packaging 📦

#7238 qt send tab: when clicking "Max", show tooltip explaining max amt
  electrum/gui/qt/main_window.py
Labels: user-interface 🔲
