Repository spesmilo/electrum, pull requests merged in 2023-05, with the labels that each got.

#8417 wallet_db version 52: break non-homogeneous multisig wallets
  electrum/gui/qml/components/main.qml
  electrum/gui/qml/qedaemon.py
  electrum/gui/qml/qewalletdb.py
  electrum/gui/qt/__init__.py
  electrum/util.py
  electrum/wallet.py
  electrum/wallet_db.py
Labels: topic-walletstorage 💾

#8454 config: introduce ConfigVars (take 3)
  electrum/address_synchronizer.py
  electrum/base_crash_reporter.py
  electrum/base_wizard.py
  electrum/coinchooser.py
  electrum/commands.py
  electrum/contacts.py
  electrum/daemon.py
  electrum/exchange_rate.py
  electrum/gui/kivy/main_window.py
  electrum/gui/kivy/uix/dialogs/crash_reporter.py
  electrum/gui/kivy/uix/dialogs/fee_dialog.py
  electrum/gui/kivy/uix/dialogs/settings.py
  electrum/gui/kivy/uix/screens.py
  electrum/gui/qml/qeapp.py
  electrum/gui/qml/qechannelopener.py
  electrum/gui/qml/qeconfig.py
  electrum/gui/qml/qedaemon.py
  electrum/gui/qml/qefx.py
  electrum/gui/qml/qeinvoice.py
  electrum/gui/qml/qetxfinalizer.py
  electrum/gui/qt/__init__.py
  electrum/gui/qt/address_list.py
  electrum/gui/qt/confirm_tx_dialog.py
  electrum/gui/qt/exception_window.py
  electrum/gui/qt/fee_slider.py
  electrum/gui/qt/history_list.py
  electrum/gui/qt/installwizard.py
  electrum/gui/qt/main_window.py
  electrum/gui/qt/my_treeview.py
  electrum/gui/qt/network_dialog.py
  electrum/gui/qt/new_channel_dialog.py
  electrum/gui/qt/qrreader/qtmultimedia/camera_dialog.py
  electrum/gui/qt/receive_tab.py
  electrum/gui/qt/settings_dialog.py
  electrum/gui/qt/swap_dialog.py
  electrum/gui/qt/transaction_dialog.py
  electrum/gui/qt/util.py
  electrum/gui/text.py
  electrum/interface.py
  electrum/lnpeer.py
  electrum/lnworker.py
  electrum/logging.py
  electrum/network.py
  electrum/paymentrequest.py
  electrum/plugins/ledger/ledger.py
  electrum/plugins/payserver/payserver.py
  electrum/plugins/payserver/qt.py
  electrum/plugins/trustedcoin/qt.py
  electrum/plugins/trustedcoin/trustedcoin.py
  electrum/simple_config.py
  electrum/submarine_swaps.py
  electrum/tests/test_daemon.py
  electrum/tests/test_lnpeer.py
  electrum/tests/test_simple_config.py
  electrum/tests/test_sswaps.py
  electrum/tests/test_wallet_vertical.py
  electrum/util.py
  electrum/verifier.py
  electrum/wallet.py
  run_electrum
Labels: topic-config

#8459 bitbox02: update to 6.2.0 to fix a bug on macOS 13.3, and ability to display amount in sats on the device
  contrib/deterministic-build/requirements-hw.txt
  contrib/requirements/requirements-hw.txt
  electrum/plugins/bitbox02/bitbox02.py
Labels: hw-digitalbitbox
