Repository spesmilo/electrum, pull requests merged in 2024-10, with the labels that each got.

#9221 android: rm APK_VERSION, and change versionCode calculation
  contrib/add_cosigner
  contrib/android/Dockerfile
  contrib/android/buildozer_qml.spec
  contrib/android/get_apk_versioncode.py
  contrib/android/make_apk.sh
  contrib/make_download
  contrib/print_electrum_version.py
  contrib/release.sh
  electrum/version.py
Labels: OS-android🤖

#7154 commands: extend "importprivkey" to allow importing a list of keys
  electrum/commands.py
  tests/test_commands.py
Labels: CLI/RPC ▶

#9258 interface: disable ssl.VERIFY_X509_STRICT for self-signed certs
  electrum/interface.py
Labels: topic-network 🕸

#9275 qml: qetxfinalizer: use wallet.get_tx_fee_warning in all subclasses
  electrum/gui/qml/qetxfinalizer.py
Labels: gui-qml

#9250 network: use TOR stream isolation
  electrum/interface.py
  electrum/lntransport.py
  electrum/lnworker.py
  electrum/network.py
  electrum/util.py
  tests/test_lntransport.py
  tests/test_network.py
Labels: privacy 🕵️‍♂️
