Repository spesmilo/electrum, pull requests merged in 2025-08, with the labels that each got.

#10082 cli: return closest htlc expiry from check_hold_invoice
  electrum/commands.py
  tests/test_commands.py
Labels: CLI/RPC ▶

#10067 cli: add max_cltv, max_fee_msat parameters to lnpay
  electrum/commands.py
  electrum/lnutil.py
  electrum/lnworker.py
  tests/test_lnpeer.py
Labels: CLI/RPC ▶

#10015 logging: add "only_once=False" param to logger.info/warning/etc calls
  electrum/i18n.py
  electrum/logging.py
Labels: topic-logging 🧾

#10111 interface: don't request same tx from server that we just broadcast to it
  electrum/interface.py
  electrum/lrucache.py
  electrum/network.py
  tests/__init__.py
  tests/test_interface.py
  tests/test_lntransport.py
Labels: topic-network 🕸

#10133 qml: reduce tx history timestamp precision
  electrum/gui/qml/qetransactionlistmodel.py
  tests/test_qml_qetransactionlistmodel.py
Labels: gui-qml

#10131 commands: add back from_height/to_height params to onchain_history
  electrum/commands.py
  electrum/util.py
  electrum/wallet.py
  tests/fiat_fx_data/BitFinex_EUR
  tests/test_commands.py
Labels: CLI/RPC ▶

#10167 commands: use format_satoshis consistently. don't use sci-notation
  electrum/commands.py
  electrum/util.py
  tests/test_commands.py
Labels: CLI/RPC ▶
