Repository spesmilo/electrum, pull requests merged in 2025-03, with the labels that each got.

#9600 config: raise on setting mistyped or non-existent ConfigVar
  electrum/simple_config.py
  tests/test_simple_config.py
Labels: topic-config

#9542 Introduce incoming gossip query handling and forwarding
  electrum/channel_db.py
  electrum/lnpeer.py
  electrum/lntransport.py
  electrum/lnutil.py
  electrum/lnworker.py
  tests/test_lnpeer.py
Labels: lightning ⚡

#9587 Disable mpp flags in invoice creation if jit channel is required and consider available liquidity
  electrum/lnpeer.py
  electrum/lnworker.py
Labels: lightning ⚡

#9586 Add mechanism to block htlcs from settling back
  electrum/lnpeer.py
  electrum/lnworker.py
  tests/test_lnpeer.py
Labels: lightning ⚡

#9633 Use FeePolicy in qeswaphelper to fix exception
  electrum/gui/qml/qeswaphelper.py
Labels: lightning ⚡, gui-qml

#9598 Handle zeroconf lightning requests in QT gui
  electrum/gui/qt/receive_tab.py
  electrum/wallet.py
Labels: lightning ⚡

#9636 wallet: add new config option "FREEZE_REUSED_ADDRESS_UTXOS"
  electrum/address_synchronizer.py
  electrum/gui/qt/confirm_tx_dialog.py
  electrum/simple_config.py
  electrum/wallet.py
Labels: topic-wallet 👛

#9634 wallet: consider "future" coins as frozen by default
  electrum/gui/qt/main_window.py
  electrum/wallet.py
Labels: topic-wallet 👛

#9638 Fix anchor output sweeping bug creating invalid sweeping tx
  electrum/coinchooser.py
  electrum/wallet.py
  tests/test_coinchooser.py
  tests/test_txbatcher.py
Labels: lightning ⚡

#9629 Allow plugins to register CLI commands
  electrum/commands.py
  electrum/daemon.py
  electrum/plugin.py
  electrum/plugins/labels/commands.py
  electrum/plugins/labels/labels.py
  run_electrum
Labels: CLI/RPC ▶

#9652 plugins: ledger: rm support for hw.1
  contrib/build-wine/deterministic.spec
  contrib/deterministic-build/requirements-hw.txt
  contrib/osx/osx.spec
  contrib/requirements/requirements-hw.txt
  electrum/plugins/hw_wallet/plugin.py
  electrum/plugins/ledger/auth2fa.py
  electrum/plugins/ledger/ledger.py
  electrum/plugins/ledger/qt.py
Labels: hw-ledger

#9655 plugins: better handle exceptions in `__init__`
  electrum/plugin.py
Labels: topic-plugins

#9656 plugin ConfigVars: define vars less dynamically
  electrum/plugin.py
  electrum/plugins/payserver/__init__.py
  electrum/plugins/swapserver/__init__.py
  electrum/plugins/watchtower/__init__.py
  electrum/simple_config.py
Labels: topic-config, topic-plugins
