Repository spesmilo/electrum, pull requests merged in 2025-04, with the labels that each got.

#9689 lightning: don't use fallback feerates for lightning fee estimation
  electrum/lnpeer.py
  electrum/lnworker.py
  tests/test_lnpeer.py
Labels: lightning ⚡

#9664 build: partial rerun freeze_packages
  contrib/build-linux/appimage/make_appimage.sh
  contrib/build-wine/build-electrum-git.sh
  contrib/deterministic-build/requirements-build-base.txt
  contrib/deterministic-build/requirements.txt
  contrib/make_packages.sh
  contrib/osx/make_osx.sh
  contrib/requirements/requirements-build-base.txt
Labels: build/packaging 📦

#9692 lightning: don't use frozen channels from route hint
  electrum/lnworker.py
Labels: lightning ⚡

#9640 swaps: Update submarine swap nostr relays dynamically and remove redundant query
  electrum/submarine_swaps.py
Labels: enhancement ✨

#9696 lightning: fix exception if LIGHTNING_LISTEN is not set on public node
  electrum/lnpeer.py
Labels: bug 🐞, lightning ⚡

#9703 qml: call QEChannelOpener.validate() on updateMaxAmount
  electrum/gui/qml/qechannelopener.py
Labels: bug 🐞, gui-qml

#9675 plugin: implement Nostr Wallet Connect (NIP47) plugin
  electrum/gui/common_qt/util.py
  electrum/lnpeer.py
  electrum/lnworker.py
  electrum/plugins/nwc/__init__.py
  electrum/plugins/nwc/cmdline.py
  electrum/plugins/nwc/manifest.json
  electrum/plugins/nwc/nwcserver.py
  electrum/plugins/nwc/qt.py
  electrum/plugins/revealer/qt.py
  electrum/simple_config.py
  electrum/util.py
  electrum/wallet.py
Labels: lightning ⚡

#9707 lightning: trigger payment_failed only once in LNWallet.htlc_failed().
  electrum/lnworker.py
Labels: lightning ⚡

#9723 lightning: prevent usage of unavailable channels for payment
  electrum/lnrouter.py
Labels: bug 🐞, lightning ⚡

#9731 lightning: remove LIGHTNING_LEGACY_ADD_TRAMPOLINE config option
  electrum/gui/qt/settings_dialog.py
  electrum/lnworker.py
  electrum/simple_config.py
Labels: lightning ⚡

#9763 qt: fix OverlayControlMixin.add_menu_button type error, fix type hints
  electrum/gui/qt/util.py
Labels: bug 🐞

#9749 add harden_memory_linux: harder for other processes to read our memory
  electrum/harden_memory_linux.py
  run_electrum
Labels: OS-linux 🐧

#9769 fix: PluginsDialog bugs causing exceptions
  electrum/gui/qt/plugins_dialog.py
  electrum/plugin.py
Labels: bug 🐞, gui-qt-desktop
